CREATE TABLE INVENTORY(
	ID BIGINT NOT NULL DEFAULT NEXTVAL('INVENTORY_ID_SEQ'::REGCLASS),
	ITEM_ID BIGINT NOT NULL,
	QUANTITY INT,
	WEIGHT NUMERIC(7,2),
	STOCKED_DATE DATE NOT NULL,
	EXPIRATION_DATE DATE,
	CREATED_DATE TIMESTAMP NOT NULL,
	MODIFIED_DATE TIMESTAMP NOT NULL,
	CONSTRAINT INVENTORY_ID_PKEY PRIMARY KEY (ID),
	CONSTRAINT ITEM_INVENTORY_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID)
);

CREATE SEQUENCE INVENTORY_ID_SEQ;