CREATE TABLE ITEM(
	ID BIGINT NOT NULL DEFAULT NEXTVAL('ITEM_ID_SEQ'::REGCLASS),
	NAME VARCHAR NOT NULL,
	DESCRIPTION VARCHAR,
	PRICE NUMERIC(7,2) NOT NULL,
	CATEGORY VARCHAR,
	SELLING_TYPE varchar NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	MODIFIED_DATE TIMESTAMP NOT NULL,
	CONSTRAINT ITEM_ID_PKEY PRIMARY KEY (ID)
);

CREATE SEQUENCE ITEM_ID_SEQ;