CREATE TABLE USER_DETAIL(
	USERID bigint NOT NULL DEFAULT nextval('user_detail_userid_seq'::regclass),
	NAME VARCHAR NOT NULL,
	USERNAME VARCHAR,
	PASSWORD VARCHAR NOT NULL,
	EMAIL VARCHAR,
	ROLE VARCHAR NOT NULL DEFAULT 'USER',
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_LOGIN TIMESTAMP,
	CONSTRAINT USER_DETAIL_PKEY PRIMARY KEY (USERID),
	UNIQUE(EMAIL),
	UNIQUE(USERNAME)
);

CREATE SEQUENCE user_detail_userid_seq;
